# Generated by Django 5.2.7 on 2025-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS trg_lote_after_update;
            CREATE TRIGGER trg_lote_after_update
            AFTER UPDATE ON lote
            FOR EACH ROW
            BEGIN
              DECLARE diff INT;
              SET diff = CAST(NEW.cantidad_disponible AS SIGNED) - CAST(OLD.cantidad_disponible AS SIGNED);
              IF diff <> 0 THEN
                UPDATE producto
                  SET stock_actual = stock_actual + diff
                  WHERE id = NEW.producto_id;
              END IF;

              IF NEW.producto_id <> OLD.producto_id THEN
                CALL sp_recalcular_costo_promedio_por_producto(OLD.producto_id);
                CALL sp_recalcular_costo_promedio_por_producto(NEW.producto_id);
              ELSE
                CALL sp_recalcular_costo_promedio_por_producto(NEW.producto_id);
              END IF;
            END;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_lote_after_update;
            CREATE TRIGGER trg_lote_after_update
            AFTER UPDATE ON lote
            FOR EACH ROW
            BEGIN
              DECLARE diff INT;
              SET diff = NEW.cantidad_disponible - OLD.cantidad_disponible;
              IF diff <> 0 THEN
                UPDATE producto
                  SET stock_actual = stock_actual + diff
                  WHERE id = NEW.producto_id;
              END IF;

              IF NEW.producto_id <> OLD.producto_id THEN
                CALL sp_recalcular_costo_promedio_por_producto(OLD.producto_id);
                CALL sp_recalcular_costo_promedio_por_producto(NEW.producto_id);
              ELSE
                CALL sp_recalcular_costo_promedio_por_producto(NEW.producto_id);
              END IF;
            END;
            """
        )
    ]
