# Generated by Django 5.2.7 on 2025-12-01 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_productocanjeble_producto_inventario'),
        ('inventory', '0003_tasaiva'),
        ('pos', '0003_fix_trigger_stock_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta_abierta', models.BooleanField(default=False)),
                ('total_cuenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.cliente')),
            ],
            options={
                'db_table': 'mesa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('facturado', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.mesa')),
            ],
            options={
                'db_table': 'item_mesa',
            },
        ),
    ]
