# Generated by Django 5.2.7 on 2025-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_mesa_itemmesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmesa',
            name='anotacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
