# Generated by Django 5.2.7 on 2025-12-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Agregar columnas de Django si no existen
            SET @sql = '';
            
            -- Verificar y agregar is_staff
            SELECT COUNT(*) INTO @col_exists FROM information_schema.columns 
            WHERE table_schema = DATABASE() AND table_name = 'usuario' AND column_name = 'is_staff';
            
            IF @col_exists = 0 THEN
                SET @sql = CONCAT(@sql, 'ALTER TABLE usuario ADD COLUMN is_staff TINYINT(1) NOT NULL DEFAULT 0;');
            END IF;
            
            -- Verificar y agregar is_superuser
            SELECT COUNT(*) INTO @col_exists FROM information_schema.columns 
            WHERE table_schema = DATABASE() AND table_name = 'usuario' AND column_name = 'is_superuser';
            
            IF @col_exists = 0 THEN
                SET @sql = CONCAT(@sql, 'ALTER TABLE usuario ADD COLUMN is_superuser TINYINT(1) NOT NULL DEFAULT 0;');
            END IF;
            
            -- Ejecutar SQL si hay cambios
            IF LENGTH(@sql) > 0 THEN
                SET @sql = CONCAT(@sql, '');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            END IF;
            """,
            reverse_sql="""
            ALTER TABLE usuario DROP COLUMN IF EXISTS is_staff;
            ALTER TABLE usuario DROP COLUMN IF EXISTS is_superuser;
            """
        ),
    ]