# Generated by Django 5.2.7 on 2025-12-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE usuario 
            ADD COLUMN IF NOT EXISTS is_staff TINYINT(1) NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS is_superuser TINYINT(1) NOT NULL DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE usuario DROP COLUMN IF EXISTS is_staff;
            ALTER TABLE usuario DROP COLUMN IF EXISTS is_superuser;
            """
        ),
    ]