# Generated by Django 5.2.8 on 2025-12-10 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_alter_pqrs_options_alter_pqrsevento_pqrs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pqrs_adjunto',
                'ordering': ['-fecha_subida'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pqrs',
            options={'managed': False, 'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='pqrsevento',
            options={'managed': False, 'ordering': ['-fecha_evento']},
        ),
    ]
