# Generated by Django 5.2.7 on 2025-12-15 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_alter_pqrs_options_alter_pqrsevento_pqrs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pqrs_adjunto',
                'ordering': ['-fecha_subida'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '⭐ Muy malo'), (2, '⭐⭐ Malo'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pqrs_calificacion',
                'ordering': ['-fecha_calificacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsCategoriaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Categoría Personalizada',
                'verbose_name_plural': 'Categorías Personalizadas',
                'db_table': 'pqrs_categoria_personalizada',
                'ordering': ['orden', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsEscalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_escalamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pqrs_escalamiento',
                'ordering': ['-fecha_escalamiento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('sistema', 'Sistema')], max_length=10)),
                ('destinatario', models.CharField(max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'pqrs_notificacion',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsPlantillaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('general', 'General'), ('producto', 'Producto'), ('servicio', 'Servicio'), ('entrega', 'Entrega')], max_length=50, null=True)),
                ('contenido', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Respuesta',
                'verbose_name_plural': 'Plantillas de Respuesta',
                'db_table': 'pqrs_plantilla_respuesta',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsSla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20)),
                ('horas_limite', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SLA de PQRS',
                'verbose_name_plural': 'SLAs de PQRS',
                'db_table': 'pqrs_sla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsVistaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('filtros', models.JSONField()),
                ('es_publica', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Vista Guardada',
                'verbose_name_plural': 'Vistas Guardadas',
                'db_table': 'pqrs_vista_guardada',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pqrs',
            options={'managed': False, 'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='pqrsevento',
            options={'managed': False, 'ordering': ['-fecha_evento']},
        ),
    ]
