# Generated by Django 5.2.8 on 2025-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de IVA (ej. 19.00 para 19%)', max_digits=5)),
            ],
            options={
                'db_table': 'tasa_iva',
                'managed': False,
            },
        ),
    ]
