"""
Django settings for la_playita_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent


# =======================
# Seguridad básica
# =======================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-^(rk4r&@kj)93sjzv49k-^a+ua-&cyp!mu499jg5aj0!j2z3*i"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Railway hostname
RAILWAY_STATIC_URL = os.environ.get("RAILWAY_STATIC_URL")
if RAILWAY_STATIC_URL and RAILWAY_STATIC_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

# Render hostname (legacy)
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# =======================
# Apps
# =======================

INSTALLED_APPS = [
    "users.apps.UsersConfig",  # ← debe estar primero

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "widget_tweaks",
    "rest_framework",
    "corsheaders",

    "core.apps.CoreConfig",
    "inventory.apps.InventoryConfig",
    "pos.apps.PosConfig",
    "pqrs.apps.PqrsConfig",
    "suppliers.apps.SuppliersConfig",
    "clients.apps.ClientsConfig",
    "reportes",
]


# =======================
# Middleware
# =======================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "la_playita_project.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.role_flags",
            ],
        },
    },
]


WSGI_APPLICATION = "la_playita_project.wsgi.application"


# =======================
# Base de datos
# =======================
# Producción: usa DATABASE_URL (Railway)
# Desarrollo: tu configuración actual local (localhost:3309)

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ["DATABASE_URL"],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "laplayita",
            "USER": "root",
            "PASSWORD": "12345678",
            "HOST": "localhost",
            "PORT": "3309",
        }
    }


# =======================
# Autenticación
# =======================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/users/login/"

AUTH_USER_MODEL = "users.Usuario"


# =======================
# Sesiones seguras
# =======================

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 minutos
SESSION_SAVE_EVERY_REQUEST = True

# Solo usar cookies seguras en producción
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True


# =======================
# Internacionalización
# =======================

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_L10N = True
USE_TZ = True


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =======================
# Archivos estáticos
# =======================

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# WhiteNoise configuration - Configuración básica
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br']


# =======================
# Media
# =======================

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# =======================
# Migraciones (legacy)
# =======================

class DisableMigrations(dict):
    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None

# MIGRATION_MODULES = DisableMigrations()


# =======================
# Email Configuration
# =======================

# FORZAR SENDGRID EN RAILWAY - Configuración usando variables de entorno
if os.environ.get("DATABASE_URL"):  # Detectar que estamos en Railway
    # CONFIGURACIÓN SENDGRID FORZADA PARA RAILWAY
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.environ.get("SENDGRID_FROM_EMAIL", "soporte.laplayita@gmail.com")
    EMAIL_TIMEOUT = 30
    
    print("🔧 RAILWAY DETECTADO - USANDO SENDGRID")
    print(f"📧 EMAIL_HOST: {EMAIL_HOST}")
    print(f"📧 EMAIL_HOST_USER: {EMAIL_HOST_USER}")
    print(f"📧 DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
    print(f"📧 EMAIL_HOST_PASSWORD configurado: {'Sí' if EMAIL_HOST_PASSWORD else 'No'}")
    
else:
    # CONFIGURACIÓN LOCAL (desarrollo)
    EMAIL_PROVIDER = os.environ.get("EMAIL_PROVIDER", "gmail")
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "30"))

    # Configuración según el proveedor
    if EMAIL_PROVIDER == "sendgrid":
        # CONFIGURACIÓN SENDGRID PARA DESARROLLO
        EMAIL_HOST = "smtp.sendgrid.net"
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
        EMAIL_HOST_USER = "apikey"
        EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
        DEFAULT_FROM_EMAIL = "soporte.laplayita@gmail.com"
        
    elif EMAIL_PROVIDER == "mailgun":
        EMAIL_HOST = "smtp.mailgun.org"
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = os.environ.get("MAILGUN_SMTP_LOGIN", "")
        EMAIL_HOST_PASSWORD = os.environ.get("MAILGUN_SMTP_PASSWORD", "")
        DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
        
    elif EMAIL_PROVIDER == "outlook":
        EMAIL_HOST = "smtp-mail.outlook.com"
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
        EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
        DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
        
    else:
        # CONFIGURACIÓN GMAIL (por defecto local)
        EMAIL_HOST = "smtp.gmail.com"
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = "soporte.laplayita@gmail.com"
        EMAIL_HOST_PASSWORD = "mafqcymwowaxzvdb"
        DEFAULT_FROM_EMAIL = "soporte.laplayita@gmail.com"

    # En desarrollo, usar backend de consola si no hay configuración de correo
    if DEBUG and not EMAIL_HOST_PASSWORD:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# =======================
# Logging
# =======================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "django.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "suppliers": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# =======================
# Django REST Framework
# =======================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
}


# =======================
# CORS
# =======================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_CREDENTIALS = True

# =======================
# CSRF Configuration for Railway
# =======================

# Permitir CSRF desde cualquier origen en producción
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://*.up.railway.app',
]

# También agregar el dominio específico si existe
if RAILWAY_STATIC_URL:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_STATIC_URL}')

# Agregar todos los hosts permitidos a CSRF_TRUSTED_ORIGINS
for host in ALLOWED_HOSTS:
    if host != '*' and host:
        if not host.startswith('http'):
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
            CSRF_TRUSTED_ORIGINS.append(f'http://{host}')

# En desarrollo, permitir localhost
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Configuración adicional de seguridad
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_TZ = True

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo/testing
CORS_ALLOW_CREDENTIALS = True