"""
Django settings for la_playita_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent


# =======================
# Seguridad básica
# =======================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-^(rk4r&@kj)93sjzv49k-^a+ua-&cyp!mu499jg5aj0!j2z3*i"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Railway hostname
RAILWAY_STATIC_URL = os.environ.get("RAILWAY_STATIC_URL")
if RAILWAY_STATIC_URL and RAILWAY_STATIC_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

# Render hostname (legacy)
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# =======================
# Apps
# =======================

INSTALLED_APPS = [
    "users.apps.UsersConfig",  # ← debe estar primero

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "widget_tweaks",
    "rest_framework",
    "corsheaders",

    "core.apps.CoreConfig",
    "inventory.apps.InventoryConfig",
    "pos.apps.PosConfig",
    "pqrs.apps.PqrsConfig",
    "suppliers.apps.SuppliersConfig",
    "clients.apps.ClientsConfig",
    "reportes",
]


# =======================
# Middleware
# =======================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "la_playita_project.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.role_flags",
            ],
        },
    },
]


WSGI_APPLICATION = "la_playita_project.wsgi.application"


# =======================
# Base de datos
# =======================
# Producción: usa DATABASE_URL (Railway)
# Desarrollo: MySQL local (localhost:3309)

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ["DATABASE_URL"],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "laplayita",
            "USER": "root",
            "PASSWORD": "12345678",
            "HOST": "localhost",
            "PORT": "3309",
        }
    }


# =======================
# Autenticación
# =======================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/users/login/"

AUTH_USER_MODEL = "users.Usuario"


# =======================
# Sesiones seguras
# =======================

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 minutos
SESSION_SAVE_EVERY_REQUEST = True

# Solo usar cookies seguras en producción
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True


# =======================
# Internacionalización
# =======================

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_L10N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =======================
# Archivos estáticos
# =======================

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# =======================
# Media
# =======================

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# =======================
# Migraciones (legacy)
# =======================

class DisableMigrations(dict):
    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None

# MIGRATION_MODULES = DisableMigrations()


# =======================
# Email Configuration
# =======================

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")

# En producción con Resend: usar API HTTP (evita bloqueo SMTP de Railway)
if RESEND_API_KEY and not DEBUG:
    EMAIL_BACKEND = "core.resend_backend.ResendEmailBackend"
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "onboarding@resend.dev")

# En desarrollo: usar Gmail SMTP
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = "soporte.laplayita@gmail.com"
    EMAIL_HOST_PASSWORD = "mafqcymwowaxzvdb"
    DEFAULT_FROM_EMAIL = "soporte.laplayita@gmail.com"
    EMAIL_TIMEOUT = 30



# =======================
# Logging
# =======================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "django.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "suppliers": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# =======================
# Django REST Framework
# =======================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
}


# =======================
# CORS
# =======================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_CREDENTIALS = True

# Solo para desarrollo/testing; en producción conviene restringir
CORS_ALLOW_ALL_ORIGINS = True


# =======================
# CSRF Configuration for Railway
# =======================

CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app",
    "https://*.up.railway.app",
]

if RAILWAY_STATIC_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_STATIC_URL}")

for host in ALLOWED_HOSTS:
    if host and host != "*":
        if not host.startswith("http"):
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
            CSRF_TRUSTED_ORIGINS.append(f"http://{host}")


# Configuración adicional de seguridad
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_TZ = True
