# Generated by Django 5.2.8 on 2025-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_add_audit_and_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaReabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('recibido', 'Recibido'), ('editado', 'Editado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('cantidad_anterior', models.IntegerField(blank=True, null=True)),
                ('cantidad_nueva', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_reabastecimiento',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
    ]
