# Generated by Django 5.2.7 on 2025-11-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE cliente ADD COLUMN puntos_totales DECIMAL(10, 2) DEFAULT 0.00;",
            reverse_sql="ALTER TABLE cliente DROP COLUMN puntos_totales;"
        )
    ]
