# Generated by Django 5.2.7 on 2025-11-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos_totales',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
