# Generated by Django 5.2.7 on 2025-11-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_loyalty_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCanjeble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntos_requeridos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producto_canjeble',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CanjeProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_gastados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.productocanjeble')),
            ],
            options={
                'db_table': 'canje_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PuntosFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganancia', 'Ganancia por Compra'), ('canje', 'Canje de Producto'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.canjeproducto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
            ],
            options={
                'db_table': 'puntos_fidelizacion',
                'managed': True,
            },
        ),
    ]
