# Generated by Django 5.2.7 on 2025-11-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_create_loyalty_tables'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocanjeble',
            name='producto_inventario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_canje', to='inventory.producto'),
        ),
    ]
